Remove minSdkVersion Due to Android Studio Error
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Remove minSdkVersion and sync project
Affected Modules: react-native-i18n.android.react-native-i18n